-- 请在这个文件中添加需要增加的系统级选项和初始化的用户级选项
-- 添加方式为在文件尾部追加定义的选项列表，默认语句格式为：
-- INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), '$选项类型', '$选项类型说明',  '1', '$选项的显示内容', '$选项的值', '$排序序号', now(), '$Locale', $是否系统选项);
-- 请注意： 添加前请先检查数据表中是否已经存在可以使用的选项列表，如果有不要重复添加，比如通用的YesNo等
-- 上述例子中空的位置都需要填写内容，新增好的sql语句需交给SA审核检查是否符合设计和符合代码规范
-- 不同 $Locale 需要写在不同的块中，默认写zh-CN 块，里面填写的值都是 'zh-CN' 
-- 必须定义选项是属于系统级还是用户级的，定义需符合设计规范

-- CLEAR ALL
DELETE FROM t_sys_choose_option;
--需要时使用,序列重新编号
--select setval('S_T_SYS_CHOOSE_OPTION',1,false);

-- 'zh-CN' 块
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'IS_AVAILABLE', '是否有效',  '1', '有效', '1', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'IS_AVAILABLE', '是否有效',  '1', '无效', '0', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'TRUE_OR_FALSE', '是或否',  '1', '是', 'true', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'TRUE_OR_FALSE', '是或否',  '1', '否', 'false', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EDITING_TYPE', '编辑类型',  '1', '单行输入', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EDITING_TYPE', '编辑类型',  '1', '可输入单选', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EDITING_TYPE', '编辑类型',  '1', '单选', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EDITING_TYPE', '编辑类型',  '1', '多选', '4', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EDITING_TYPE', '编辑类型',  '1', '自定义多选', '5', '5', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'VALUE_TYPE', '值类型',  '1', '文本', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'VALUE_TYPE', '值类型',  '1', '数值', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'VALUE_TYPE', '值类型',  '1', '日期', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'VALUE_TYPE', '值类型',  '1', '日期时间', '4', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_SOURCE', '值类型', '1', '自注册', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_SOURCE', '值类型', '1', 'QQ登录', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_SOURCE', '值类型',  '1', '新浪登录', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_SOURCE', '值类型',  '1', '支付宝登录', '4', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_TYPE', '会员类型', '1', '自有会员', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_TYPE', '会员类型',  '1', '自注册会员', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_TYPE', '会员类型',  '1', '第三方会员', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_ISBIND', '是否绑定',  '1', '已绑定', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_ISBIND', '是否绑定',  '1', '未绑定', '0', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_SEX', '性别',  '1', '男', '0', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_SEX', '性别',  '1', '女', '1', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_CREDENTIALTYPE', '证件类型', '1', '身份证', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_CREDENTIALTYPE', '证件类型',  '1', '学生证', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_CREDENTIALTYPE', '证件类型',  '1', '军官证', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'TEMPLATE_TYPE', 'cms模板定义类型',  '1', '静态', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'TEMPLATE_TYPE', 'cms模板定义类型',  '1', '动态', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_TYPE', '属性类型',  '1', '原子类型', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_TYPE', '属性类型',  '1', '组合类型', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_TYPE', '属性类型',  '1', '列表类型', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_EDITER', '属性编辑器',  '1', 'date', 'date', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_EDITER', '属性编辑器',  '1', 'string', 'string', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_EQUIRED', '是否必须', '1', '是', 'true', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROP_EQUIRED', '是否必须', '1', '否', 'false', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RESOURCE_TYPE', 'cms资源管理资源类型',  '1', '文件夹', 'nt:folder', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RESOURCE_TYPE', 'cms资源管理资源类型',  '1', '文件', 'nt:file', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '新建', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '已同步oms', '3', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '库存已确认', '4', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '库房准备中', '5', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '在途', '6', '5', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '会员取消', '9', '6', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '商城取消', '10', '7', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_LOGISTICS', '订单物流状态',  '1', '交易完成', '15', '8', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_FINANCIAL', '订单财务状态',  '1', '未付款', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_STATUS_FINANCIAL', '订单财务状态',  '1', '已全额收款', '3', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_SOURCE', '订单来源', '1', '官方商城', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_SOURCE', '订单来源',  '1', '第三方订单', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_SOURCE', '订单来源',  '1', '手机端订单', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_TYPE', '发票类型',  '1', '普通发票', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_TYPE', '发票类型',  '1', '增值税发票', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_PAYTYPE_TYPE', '支付方式', '1', '在线支付&&通过网银支付', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_PAYTYPE_TYPE', '支付方式', '1', '货到付款&&送货上门后再收款，支持现金、POS机刷卡、支票支付 查看服务及配送范围', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_PAYTYPE_TYPE', '支付方式',  '1', '延迟付款&&不当场付钱，线下方式付款', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_LINE_EVALUATION', '是否评价', '1', '未评价', '0', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_LINE_EVALUATION', '是否评价',  '1', '已评价', '1', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_LINE_TYPE', '行类型',  '1', '主卖品', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_LINE_TYPE', '行类型',  '1', '赠品', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EXPRESS', '快递公司', '1', '顺丰', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EXPRESS', '快递公司',  '1', 'EMS', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_EXPRESS', ' 快递公司',  '1', '顺丰', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_EXPRESS', ' 快递公司',  '1', 'EMS', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_APPOINTTIME', '送货时间',  '1', '只工作日送货', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_APPOINTTIME', '送货时间',  '1', '工作日、双休日与假日均可送货', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_APPOINTTIME', '送货时间',  '1', '只双休日、假日送货', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_TITLE', '发票抬头',  '1', '单位', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_TITLE', '发票抬头',  '1', '个人', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_CONTENT', '发票内容',  '1', '明细', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_CONTENT', '发票内容',  '1', '办公用品', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_CONTENT', '发票内容',  '1', '电脑配件', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RECEIPT_CONTENT', '发票内容',  '1', '耗材', '4', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CANCEL_ORDER_STATUS', '申请取消订单状态',  '1', '新建', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CANCEL_ORDER_STATUS', '申请取消订单状态',  '1', '处理完成', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RETURN_ORDER_STATUS', '退换货订单状态', '1', '新建', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RETURN_ORDER_STATUS', '退换货订单状态',  '1', '审核通过', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RETURN_ORDER_STATUS', '退换货订单状态',  '1', '处理完成', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RETURN_ORDER_SERVICETYPE', '申请退换货服务类型',  '1', '退货', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'RETURN_ORDER_SERVICETYPE', '申请退换货服务类型',  '1', '换货', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_IS_RECEIPT', '有无发票',  '1', '有', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_IS_RECEIPT', '有无发票',  '1', '无', '0', '0', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_PROMOTION_TYPE', '促销类型',  '1', '满xx立减xx', '0', '0', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ORDER_PROMOTION_TYPE', '促销类型', '1', 'xx折', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CONSULTANT_STATUS', '咨询状态',  '1', '待回复', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CONSULTANT_STATUS', '咨询状态',  '1', '延时回复', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CONSULTANT_STATUS', '咨询状态',  '1', '已回复', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_STATUS', '商品状态',  '1', '上架', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_STATUS', '商品状态',  '1', '下架', '0', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_STATUS', '商品状态',  '1', '新建', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CRYPTOGUARD_QUESTION', '密保问题', '1', '1', '你的生日？', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CRYPTOGUARD_QUESTION', '密保问题',  '1', '2', '你妈妈的生日？', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CRYPTOGUARD_QUESTION', '密保问题',  '1', '3', '你的真实姓名？', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CONSULTANT_PUBLISH_MARK', '咨询是否公示',  '1', '未公示', '0', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CONSULTANT_PUBLISH_MARK', '咨询是否公示',  '1', '已公示', '1', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'NAVIGATION_TYPE', '菜单导航类型',  '1', '活动推广链接', '3', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'NAVIGATION_TYPE', '菜单导航类型', '1', '商品集合链接', '5', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'NAVIGATION_LIFECYCLE', '菜单导航状态',  '1', '有效', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'NAVIGATION_LIFECYCLE', '菜单导航状态',  '1', '无效', '0', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'IMAGE_TYPE', '图片类型',  '1', '列表页', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'IMAGE_TYPE', '图片类型',  '1', '内容页', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'IMAGE_TYPE', '图片类型',  '1', '两者都', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'IMAGE_TYPE', '图片类型',  '1', '规格图', '4', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'THUMBNAIL_CONFIG', '缩略图配置', '1', '1', '65X65|300X300|600X600', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'THUMBNAIL_CONFIG', '缩略图配置', '1', '2', '65X65|300X300|600X600', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'THUMBNAIL_CONFIG', '缩略图配置', '1', '3', '65X65|300X300|600X600', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'THUMBNAIL_CONFIG', '缩略图配置', '1', '4', '65X65|300X300|600X600', '1', now(), 'zh-CN', true);
--会员筛选器类型
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_FILTER_TYPE', '会员筛选器类型',  '1', '会员', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_FILTER_TYPE', '会员筛选器类型',  '1', '分组', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id", "group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version", "label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'MEMBER_FILTER_TYPE', '会员筛选器类型',  '1', '自定义', '3', '3', now(), 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_FILTER_TYPE', '会员筛选器类型',  '1', '组合', '4', '4', now(), 'zh-CN', true);
--商品筛选器类型
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'ITEM_FILTER_TYPE', '商品筛选器类型', '1', '商品', '1', '1', now(), 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'ITEM_FILTER_TYPE', '商品筛选器类型', '1', '分类', '2', '2', now(), 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'ITEM_FILTER_TYPE', '商品筛选器类型', '1', '自定义', '3', '3', now(), 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'ITEM_FILTER_TYPE', '商品筛选器类型', '1', '组合', '4', '4', 'now()', 'zh-CN', 't');
--促销条件
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'PROMOTION_CONDITION_TYPE', '促销条件', '1', '常规条件', 'Normal', '1', 'now()', 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'PROMOTION_CONDITION_TYPE', '促销条件', '1', '阶梯条件', 'Step', '2', 'now()', 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'PROMOTION_CONDITION_TYPE', '促销条件', '1', '套餐条件', 'Choice', '3', 'now()', 'zh-CN', 't');
INSERT INTO "t_sys_choose_option"("id", "group_code", "group_desc","lifecycle","option_label","option_value","sort_no","version","label_lang","is_system") VALUES (nextval('S_T_SYS_CHOOSE_OPTION'), 'PROMOTION_CONDITION_TYPE', '促销条件', '1', '常规+阶梯条件', 'NormalStep', '4', 'now()', 'zh-CN', 't');

INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_FILTER_BASIC_TYPE', '会员筛选器基础类型',  '1', '会员', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'MEMBER_FILTER_BASIC_TYPE', '会员筛选器基础类型',  '1', '分组', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'SEARCH_CONDITION_TYPE', '搜索选项类型',  '1', '一般类型', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'SEARCH_CONDITION_TYPE', '搜索选项类型',  '1', '区间类型', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'SEARCH_CONDITION_TYPE', '搜索选项类型',  '1', '价格类型', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'COUPON_STATE', '优惠券状态',  '1', '已使用', '1', '1', '2014-02-17 14:24:38.273', 'zh-CN', null);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'COUPON_STATE', '优惠券状态',  '1', '未使用', '0', '2', '2014-02-17 14:24:38.273', 'zh-CN', null);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'COUPON_STATE', '优惠券状态',  '1', '已过期', '-1', '3', '2014-02-17 14:24:38.273', 'zh-CN', null);

-- 推荐管理
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'RECOMMAND_TYPE', '推荐类型', '1', '公共类型', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'RECOMMAND_TYPE', '推荐类型', '1', '分类推荐', '2', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'RECOMMAND_TYPE', '推荐类型',  '1', '商品搭配', '3', '1', now(), 'zh-CN', true);

INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'RECOMMAND_PARAM', '推荐参数',  '1', '购物车', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'RECOMMAND_PARAM', '推荐参数',  '1', '列表页', '2', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'RECOMMAND_PARAM', '推荐参数',  '1', '详情页', '3', '1', now(), 'zh-CN', true);

--会员分组类型
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'MEMBER_GROUPTYPE', '分组类型',  '1', '常规', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'MEMBER_GROUPTYPE', '分组类型',  '1', '等级', '2', '2', now(), 'zh-CN', true);
-- 优惠类型下拉框
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CP_TYPE', '优惠类型',  '1', '金额', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'CP_TYPE', '优惠类型',  '1', '折扣', '2', '2', now(), 'zh-CN', true);

INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROMOTION_LOGO_MARK', '活动角标', '1',  '满减','1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROMOTION_LOGO_MARK', '活动角标', '1', '折扣', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROMOTION_LOGO_MARK', '活动角标', '1',  '优惠价','3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROMOTION_LOGO_MARK', '活动角标', '1',  '免运费', '4', '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'PROMOTION_LOGO_MARK', '活动角标', '1','赠品',  '5',  '5', now(), 'zh-CN', true);

-- 商品排序类型
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_SCORE', '排序类型', '1','分类',  '1',  '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_SCORE', '排序类型', '1','属性',  '2',  '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_SCORE', '排序类型', '1','吊牌价',  '3',  '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_SCORE', '排序类型', '1','销量',  '4',  '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_SCORE', '排序类型', '1','收藏',  '5',  '5', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_SCORE', '排序类型', '1',' 销售价',  '6',  '6', now(), 'zh-CN', true);

-- 商品排序计算类型
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_OPER', '计算类型', '1','大于',  'GREATER',  '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_OPER', '计算类型', '1','小于',  'LESS',  '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'ITEM_SORT_OPER', '计算类型', '1','等于',  'EQUAL',  '3', now(), 'zh-CN', true);

-- 模板邮件类型
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EMAIL_TEMPLATE_TYPE', '邮件模板类型', '1','html',  '1',  '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'EMAIL_TEMPLATE_TYPE', '邮件模板类型', '1','text',  '2',  '2', now(), 'zh-CN', true);

-- 告警类型
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TYPE', '邮件', '1','邮件',  '1',  '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TYPE', '短信', '1','短信',  '2',  '2', now(), 'zh-CN', true);

-- 告警级别
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_LEVEL', '低', '1','低',  '1',  '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_LEVEL', '中', '1','中',  '2',  '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_LEVEL', '高', '1','高',  '3',  '3', now(), 'zh-CN', true);

-- 告警时间
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TIME', '年', '1','年',  'y',  '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TIME', '月', '1','月',  'M',  '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TIME', '天', '1','天',  'd',  '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TIME', '小时', '1','小时',  'h',  '4', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TIME', '分钟', '1','分钟',  'm',  '5', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") VALUES (nextval('s_t_sys_choose_option'), 'WARNING_TIME', '秒', '1','秒',  's',  '6', now(), 'zh-CN', true);

--自定义筛选器
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'PRODUCT_CUSTOMIZE_FILTER', '自定义筛选器类型', '1', '商品', '1', '1', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'PRODUCT_CUSTOMIZE_FILTER', '自定义筛选器类型',  '1', '会员', '2', '2', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'PRODUCT_CUSTOMIZE_FILTER', '自定义筛选器类型',  '1', '条件', '3', '3', now(), 'zh-CN', true);
INSERT INTO "t_sys_choose_option"("id" ,"group_code","group_desc","lifecycle","option_label" ,"option_value","sort_no","version","label_lang","is_system") values(nextval('s_t_sys_choose_option'), 'PRODUCT_CUSTOMIZE_FILTER', '自定义筛选器类型',  '1', '优惠', '4', '4', now(), 'zh-CN', true);

